### ISSUE TITLE
Can't boot up

### ISSUE THREAD

**Issue by ArnisL** [llaine/cmdfm#5]
Any ideas what might be wrong?

» sh ./jukebox.sh
./jukebox.sh: 190: ./jukebox.sh: Syntax error: redirection unexpected

git commit: 64bd877
mplayer, curl installed; elementary os

**Comment by llaine** [comment]
Okay i look through the problem and fix it. See my last commit  [0bb621eb8e58d9cd3b475db2d92887a8d4f515e8](https://github.com/llaine/cmdfm/commit/0bb621eb8e58d9cd3b475db2d92887a8d4f515e8)

Also sometime the souncloud api provide a link of song which doesn't can be streamable. 
I can't figure out why.

**Comment by ArnisL** [comment]
That changed nothing

**Comment by llaine** [comment]
When you are typing : 

``` bash
$ ./jukebox -g minimal
```

The error appear ?

**Comment by ArnisL** [comment]
Unfortunately - yes
